-- Barkassen-Abrechnung (Besuchertag)
-- Einmalig im Supabase-Dashboard unter "SQL Editor" ausführen.

create table if not exists public.cash_closings (
    id                bigint generated by default as identity primary key,
    created_at        timestamptz not null default now(),
    closing_date      date not null default current_date,
    event_name        text not null,
    bartender_user_id bigint,
    bartender_name    text,
    handover_name     text,          -- Übernahme Kasse (Wechselgeld)
    closing_name      text not null, -- Abrechnung Kasse
    change_counts     jsonb not null default '{}'::jsonb, -- Wechselgeld: Anzahl je Wert
    change_total      numeric(10,2) not null default 0,
    cash_counts       jsonb not null default '{}'::jsonb, -- Gezählte Kasse: Anzahl je Wert
    cash_total        numeric(10,2) not null default 0,
    revenue_counted   numeric(10,2) not null default 0,   -- Kasse minus Wechselgeld
    revenue_system    numeric(10,2) not null default 0,   -- SOLL laut Kasse (Tablet)
    difference        numeric(10,2) not null default 0,   -- gezählt minus SOLL
    system_breakdown  jsonb not null default '{}'::jsonb  -- Barverkäufe, Verzehrkarten usw.
);

-- Die API greift wie bei den anderen Tabellen mit dem anon-Key zu.
alter table public.cash_closings enable row level security;

create policy "cash_closings_select" on public.cash_closings
    for select to anon using (true);

create policy "cash_closings_insert" on public.cash_closings
    for insert to anon with check (true);
